---
- name: Gather EC2 instance metadata
  action:  ec2_metadata_facts

- name: Undeploy Application on {{ ansible_hostname }}
  command: wget "http://{{tomcat_user}}:{{tomcat_pwd}}@{{ansible_ec2_public_ipv4}}:8080/manager/text/undeploy?path=/HelloWorld-Maven" -O - -q
